-- Lummo Studio Database Export (xddddd)
-- Timestamp: 2026-08-12T01:33:21.301Z
-- Generated by Lummo Studio

-- --------------------------------------------------------
-- Estrutura de tabla para "xdddd"
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS "xdddd" (
  "id" INTEGER PRIMARY KEY
);


-- --------------------------------------------------------
-- Estrutura de tabla para "sdadasdad"
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS "sdadasdad" (
  "id" INTEGER PRIMARY KEY
);


